name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branch: main
    paths: 
      - 'src/**'



jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting up PNPM to install packages
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: |
          pnpm build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deployment:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
